# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 714062a71656167e944315f35c6084fed7680985bf0e0e28dc8f8d13896145d63e51fc247f4bdd0101d6a0e9b80fcd55fa17a0a21ba9d30765d5cdf228e28176

test:
  secret_key_base: b3534794f1c69ea721f8abea34b63188a6b014cb6424a93fc53a3a1006a853fe9e40d2bdaecee1744f130fb1a8bfb0c2e47385e2b5907dc9baa7d65efd001a6c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
